// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysServerMonitorDao is the data access object for the table sys_server_monitor.
// You can define custom methods on it to extend its functionality as needed.
type sysServerMonitorDao struct {
	*internal.SysServerMonitorDao
}

var (
	// SysServerMonitor is a globally accessible object for table sys_server_monitor operations.
	SysServerMonitor = sysServerMonitorDao{internal.NewSysServerMonitorDao()}
)

// Add your custom methods and functionality below.
