// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysUserPostDao is the data access object for the table sys_user_post.
// You can define custom methods on it to extend its functionality as needed.
type sysUserPostDao struct {
	*internal.SysUserPostDao
}

var (
	// SysUserPost is a globally accessible object for table sys_user_post operations.
	SysUserPost = sysUserPostDao{internal.NewSysUserPostDao()}
)

// Add your custom methods and functionality below.
