// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysNoticeDao is the data access object for the table sys_notice.
// You can define custom methods on it to extend its functionality as needed.
type sysNoticeDao struct {
	*internal.SysNoticeDao
}

var (
	// SysNotice is a globally accessible object for table sys_notice operations.
	SysNotice = sysNoticeDao{internal.NewSysNoticeDao()}
)

// Add your custom methods and functionality below.
