// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysUserExternalIdentityDao is the data access object for the table sys_user_external_identity.
// You can define custom methods on it to extend its functionality as needed.
type sysUserExternalIdentityDao struct {
	*internal.SysUserExternalIdentityDao
}

var (
	// SysUserExternalIdentity is a globally accessible object for table sys_user_external_identity operations.
	SysUserExternalIdentity = sysUserExternalIdentityDao{internal.NewSysUserExternalIdentityDao()}
)

// Add your custom methods and functionality below.
