// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysPostDao is the data access object for the table sys_post.
// You can define custom methods on it to extend its functionality as needed.
type sysPostDao struct {
	*internal.SysPostDao
}

var (
	// SysPost is a globally accessible object for table sys_post operations.
	SysPost = sysPostDao{internal.NewSysPostDao()}
)

// Add your custom methods and functionality below.
