// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysUserDeptDao is the data access object for the table sys_user_dept.
// You can define custom methods on it to extend its functionality as needed.
type sysUserDeptDao struct {
	*internal.SysUserDeptDao
}

var (
	// SysUserDept is a globally accessible object for table sys_user_dept operations.
	SysUserDept = sysUserDeptDao{internal.NewSysUserDeptDao()}
)

// Add your custom methods and functionality below.
