// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysI18NLocaleDao is the data access object for the table sys_i18n_locale.
// You can define custom methods on it to extend its functionality as needed.
type sysI18NLocaleDao struct {
	*internal.SysI18NLocaleDao
}

var (
	// SysI18NLocale is a globally accessible object for table sys_i18n_locale operations.
	SysI18NLocale = sysI18NLocaleDao{internal.NewSysI18NLocaleDao()}
)

// Add your custom methods and functionality below.
