// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysI18NMessageDao is the data access object for the table sys_i18n_message.
// You can define custom methods on it to extend its functionality as needed.
type sysI18NMessageDao struct {
	*internal.SysI18NMessageDao
}

var (
	// SysI18NMessage is a globally accessible object for table sys_i18n_message operations.
	SysI18NMessage = sysI18NMessageDao{internal.NewSysI18NMessageDao()}
)

// Add your custom methods and functionality below.
