// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysI18NContentDao is the data access object for the table sys_i18n_content.
// You can define custom methods on it to extend its functionality as needed.
type sysI18NContentDao struct {
	*internal.SysI18NContentDao
}

var (
	// SysI18NContent is a globally accessible object for table sys_i18n_content operations.
	SysI18NContent = sysI18NContentDao{internal.NewSysI18NContentDao()}
)

// Add your custom methods and functionality below.
