// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dept

import (
	"lina-core/api/dept"
	deptsvc "lina-core/internal/service/dept"
)

// ControllerV1 is the department controller.
type ControllerV1 struct {
	deptSvc deptsvc.Service // department service
}

// NewV1 creates and returns a new department controller instance.
func NewV1() dept.IDeptV1 {
	return &ControllerV1{
		deptSvc: deptsvc.New(),
	}
}
