// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice

import (
	"lina-core/api/notice"
	noticesvc "lina-core/internal/service/notice"
)

// ControllerV1 is the notice controller.
type ControllerV1 struct {
	noticeSvc noticesvc.Service // notice service
}

// NewV1 creates and returns a new notice controller instance.
func NewV1() notice.INoticeV1 {
	return &ControllerV1{
		noticeSvc: noticesvc.New(),
	}
}
