// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	"lina-core/api/post"
	postsvc "lina-core/internal/service/post"
)

// ControllerV1 is the post controller.
type ControllerV1 struct {
	postSvc postsvc.Service // post service
}

// NewV1 creates and returns a new post controller instance.
func NewV1() post.IPostV1 {
	return &ControllerV1{
		postSvc: postsvc.New(),
	}
}
