// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package monitor

import (
	"lina-core/api/monitor"
	"lina-core/internal/service/auth"
	"lina-core/internal/service/servermon"
	"lina-core/internal/service/session"
)

// ControllerV1 is the system monitor controller.
type ControllerV1 struct {
	authSvc      auth.Service      // auth service
	serverMonSvc servermon.Service // server monitor service
}

// NewV1 creates and returns a new system monitor controller instance.
func NewV1() monitor.IMonitorV1 {
	return &ControllerV1{
		authSvc:      auth.New(),
		serverMonSvc: servermon.New(),
	}
}

// sessionStore returns the session store from auth service.
func (c *ControllerV1) sessionStore() session.Store {
	return c.authSvc.SessionStore()
}
