// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package demo

import (
	demoapi "lina-plugin-demo-source/backend/api/demo"
	demosvc "lina-plugin-demo-source/backend/service/demo"
)

// ControllerV1 is the plugin-demo-source controller.
type ControllerV1 struct {
	demoSvc *demosvc.Service // demo service
}

// NewV1 creates and returns a new plugin-demo-source controller instance.
func NewV1() demoapi.IDemoV1 {
	return &ControllerV1{
		demoSvc: demosvc.New(),
	}
}
