// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package demo

func boolToInt(value bool) int {
	if value {
		return 1
	}
	return 0
}
