// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package operlog

import (
	"lina-core/api/operlog"
	operlogsvc "lina-core/internal/service/operlog"
)

// ControllerV1 is the operation log controller.
type ControllerV1 struct {
	operLogSvc operlogsvc.Service // operation log service
}

// NewV1 creates and returns a new operation log controller instance.
func NewV1() operlog.IOperlogV1 {
	return &ControllerV1{
		operLogSvc: operlogsvc.New(),
	}
}
