// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// hgDeviceNodeDao is the data access object for the table hg_device_node.
// You can define custom methods on it to extend its functionality as needed.
type hgDeviceNodeDao struct {
	*internal.HgDeviceNodeDao
}

var (
	// HgDeviceNode is a globally accessible object for table hg_device_node operations.
	HgDeviceNode = hgDeviceNodeDao{internal.NewHgDeviceNodeDao()}
)

// Add your custom methods and functionality below.
