// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// hgNodeDao is the data access object for the table hg_node.
// You can define custom methods on it to extend its functionality as needed.
type hgNodeDao struct {
	*internal.HgNodeDao
}

var (
	// HgNode is a globally accessible object for table hg_node operations.
	HgNode = hgNodeDao{internal.NewHgNodeDao()}
)

// Add your custom methods and functionality below.
