// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// hgTenantWhiteDao is the data access object for the table hg_tenant_white.
// You can define custom methods on it to extend its functionality as needed.
type hgTenantWhiteDao struct {
	*internal.HgTenantWhiteDao
}

var (
	// HgTenantWhite is a globally accessible object for table hg_tenant_white operations.
	HgTenantWhite = hgTenantWhiteDao{internal.NewHgTenantWhiteDao()}
)

// Add your custom methods and functionality below.
