// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-media/backend/internal/dao/internal"
)

// hgTenantStreamConfigDao is the data access object for the table hg_tenant_stream_config.
// You can define custom methods on it to extend its functionality as needed.
type hgTenantStreamConfigDao struct {
	*internal.HgTenantStreamConfigDao
}

var (
	// HgTenantStreamConfig is a globally accessible object for table hg_tenant_stream_config operations.
	HgTenantStreamConfig = hgTenantStreamConfigDao{internal.NewHgTenantStreamConfigDao()}
)

// Add your custom methods and functionality below.
