// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tenant

import (
	tenantapi "lina-plugin-multi-tenant/backend/api/tenant"
	"lina-plugin-multi-tenant/backend/internal/service/tenantplugin"
)

// ControllerV1 is the tenant-scoped multi-tenant controller.
type ControllerV1 struct {
	tenantPluginSvc tenantplugin.Service
}

// NewV1 creates and returns a new tenant controller instance.
func NewV1() tenantapi.ITenantV1 {
	return NewControllerV1()
}

// NewControllerV1 creates and returns the concrete tenant controller instance.
func NewControllerV1() *ControllerV1 {
	return &ControllerV1{
		tenantPluginSvc: tenantplugin.New(),
	}
}
