// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	userapi "lina-core/api/user"
	"lina-core/internal/service/i18n"
	"lina-core/internal/service/menu"
	"lina-core/internal/service/orgcap"
	"lina-core/internal/service/role"
	usersvc "lina-core/internal/service/user"
)

// ControllerV1 is the user controller.
type ControllerV1 struct {
	userSvc   usersvc.Service // user service
	roleSvc   role.Service    // role service
	menuSvc   menu.Service    // menu service
	orgCapSvc orgcap.Service  // optional organization capability service
	i18nSvc   i18n.Translator // runtime translation service
}

// NewV1 creates and returns a new user controller instance.
func NewV1() userapi.IUserV1 {
	return &ControllerV1{
		userSvc:   usersvc.Instance(),
		roleSvc:   role.Instance(),
		menuSvc:   menu.Instance(),
		orgCapSvc: orgcap.Instance(),
		i18nSvc:   i18n.Instance(),
	}
}
