// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	pluginauth "lina-core/pkg/pluginservice/auth"
	authapi "lina-plugin-multi-tenant/backend/api/auth"
	v1 "lina-plugin-multi-tenant/backend/api/auth/v1"
	"lina-plugin-multi-tenant/backend/internal/service/membership"
	"lina-plugin-multi-tenant/backend/internal/service/provider"
)

// ControllerV1 is the tenant auth controller.
type ControllerV1 struct {
	authSvc       pluginauth.Service
	membershipSvc membership.Service
	provider      *provider.Provider
}

// NewV1 creates and returns a new auth controller instance.
func NewV1() authapi.IAuthV1 {
	return NewControllerV1()
}

// NewControllerV1 creates and returns the concrete auth controller instance.
func NewControllerV1() *ControllerV1 {
	return &ControllerV1{
		authSvc:       pluginauth.New(),
		membershipSvc: membership.New(),
		provider:      provider.New(),
	}
}

// toAPILoginTenant converts a service tenant option into an API DTO.
func toAPILoginTenant(item *membership.TenantInfo) *v1.LoginTenantEntity {
	if item == nil {
		return nil
	}
	return &v1.LoginTenantEntity{
		Id:     item.Id,
		Code:   item.Code,
		Name:   item.Name,
		Status: item.Status,
	}
}
